### ISSUE TITLE
Simulation of policy level data

### ISSUE THREAD

**Issue by MatthewCaseres** [JuliaActuary/LifeSimulator.jl#8]
I'm trying to simulate policy level data that is similar in nature to the data shown here - 
https://github.com/actuarialopensource/benchmarks/blob/main/data/census_dat.csv

Factors like male or female are playing a role in the probability of lapse at a given time. There are some studies that come up with advanced schemes for how to model these probabilities, but just some simple scheme like a logistic GLM is probably good enough.

**Comment by serenity4** [comment]
I added the possibility to use policy data in 909bf6f to compute lapse and mortality rates, see e.g. this new test: https://github.com/JuliaActuary/LifeSimulator.jl/blob/main/test/basiclife.jl#L107-L116

**Comment by serenity4** [comment]
I am in the process of documenting how to parametrize/create your own models, so that it will be clearer.

**Comment by serenity4** [comment]
Tada: https://juliaactuary.github.io/LifeSimulator.jl/dev/tutorial/customizing_models/
