### ISSUE TITLE
already a package in julia?

### ISSUE THREAD

**Issue by korilium** [JuliaActuary/LifeSimulator.jl#9]
Hey, is this already a package within the Julia environment or is this still in development?

**Comment by serenity4** [comment]
cc @MatthewCaseres

**Comment by serenity4** [comment]
It's been a work in progress until recently, then activity on it has stopped. The package hasn't been published and AFAIK there haven't been any plans to continue its development nor to release it. @MatthewCaseres feel free to correct me/provide further info.

**Comment by korilium** [comment]
Is it okay if I create a branch and start playing with it? I really like the idea of this package.

**Comment by serenity4** [comment]
Sure, feel free to fork it!

**Comment by MatthewCaseres** [comment]
It will be quite some time until I have bandwidth to do more open source contributions. Glad to see someone excited about the concept.
